2024-05-21 23:30:36,760 - root - INFO - Бот запущен
2024-05-21 23:33:59,598 - root - INFO - Бот запущен
2024-05-21 23:35:38,340 - root - INFO - Бот запущен
2024-05-22 22:52:45,309 - root - INFO - Бот запущен
2024-05-22 22:53:11,206 - root - ERROR - Ошибка: table users has no column named current_city
2024-05-22 22:55:03,024 - root - INFO - Бот запущен
2024-05-22 22:55:11,862 - root - ERROR - Ошибка: table users has no column named current_city
2024-05-22 22:55:26,221 - root - INFO - Бот запущен
2024-05-22 22:55:33,098 - root - ERROR - Ошибка: table users has no column named current_city
2024-05-22 22:56:50,024 - root - INFO - Бот запущен
2024-05-22 22:56:56,327 - root - ERROR - Ошибка: table users has no column named current_city
2024-05-22 23:06:14,871 - root - INFO - Бот запущен
2024-05-22 23:06:29,906 - root - INFO - Бот запущен
2024-05-22 23:06:40,802 - root - ERROR - Ошибка: table users has no column named current_city
2024-05-22 23:07:54,367 - root - INFO - Бот запущен
2024-05-22 23:08:00,513 - root - ERROR - Ошибка: table users has no column named current_city
2024-05-22 23:08:00,514 - root - ERROR - 'LIMITS'
2024-05-22 23:08:00,514 - root - ERROR - Leoprofi c id 6332228115 не смог получить ответ от нейросети
2024-05-22 23:08:00,722 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: BUTTON_DATA_INVALID
2024-05-22 23:08:00,723 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\My_programms\JetBrains\PyCharm Community Edition 2023.3.2\Тарочкин Леонид\Bots\bot_helper_in_journey\.venv\Lib\site-packages\telebot\__init__.py", line 1215, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\My_programms\JetBrains\PyCharm Community Edition 2023.3.2\Тарочкин Леонид\Bots\bot_helper_in_journey\.venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\My_programms\JetBrains\PyCharm Community Edition 2023.3.2\Тарочкин Леонид\Bots\bot_helper_in_journey\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\My_programms\JetBrains\PyCharm Community Edition 2023.3.2\Тарочкин Леонид\Bots\bot_helper_in_journey\bot.py", line 48, in user_add
    send_categories(message)
  File "C:\My_programms\JetBrains\PyCharm Community Edition 2023.3.2\Тарочкин Леонид\Bots\bot_helper_in_journey\bot.py", line 59, in send_categories
    bot.send_message(message.chat.id, f"Выбери, что хочешь сделать в городе {message.text}",
  File "C:\My_programms\JetBrains\PyCharm Community Edition 2023.3.2\Тарочкин Леонид\Bots\bot_helper_in_journey\.venv\Lib\site-packages\telebot\__init__.py", line 1751, in send_message
    apihelper.send_message(
  File "C:\My_programms\JetBrains\PyCharm Community Edition 2023.3.2\Тарочкин Леонид\Bots\bot_helper_in_journey\.venv\Lib\site-packages\telebot\apihelper.py", line 271, in send_message
    return _make_request(token, method_url, params=payload, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\My_programms\JetBrains\PyCharm Community Edition 2023.3.2\Тарочкин Леонид\Bots\bot_helper_in_journey\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\My_programms\JetBrains\PyCharm Community Edition 2023.3.2\Тарочкин Леонид\Bots\bot_helper_in_journey\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: BUTTON_DATA_INVALID

2024-05-22 23:09:35,230 - root - INFO - Бот запущен
2024-05-22 23:10:36,395 - root - INFO - Бот запущен
2024-05-22 23:10:48,509 - root - ERROR - Ошибка: table users has no column named current_city
2024-05-22 23:10:48,510 - root - ERROR - 'LIMITS'
2024-05-22 23:10:48,510 - root - ERROR - Leoprofi c id 6332228115 не смог получить ответ от нейросети
2024-05-22 23:10:48,714 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: BUTTON_DATA_INVALID
2024-05-22 23:10:48,716 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\My_programms\JetBrains\PyCharm Community Edition 2023.3.2\Тарочкин Леонид\Bots\bot_helper_in_journey\.venv\Lib\site-packages\telebot\__init__.py", line 1215, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\My_programms\JetBrains\PyCharm Community Edition 2023.3.2\Тарочкин Леонид\Bots\bot_helper_in_journey\.venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\My_programms\JetBrains\PyCharm Community Edition 2023.3.2\Тарочкин Леонид\Bots\bot_helper_in_journey\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\My_programms\JetBrains\PyCharm Community Edition 2023.3.2\Тарочкин Леонид\Bots\bot_helper_in_journey\bot.py", line 48, in user_add
    send_categories(message)
  File "C:\My_programms\JetBrains\PyCharm Community Edition 2023.3.2\Тарочкин Леонид\Bots\bot_helper_in_journey\bot.py", line 59, in send_categories
    bot.send_message(message.chat.id, f"Выбери, что хочешь сделать в городе {message.text}",
  File "C:\My_programms\JetBrains\PyCharm Community Edition 2023.3.2\Тарочкин Леонид\Bots\bot_helper_in_journey\.venv\Lib\site-packages\telebot\__init__.py", line 1751, in send_message
    apihelper.send_message(
  File "C:\My_programms\JetBrains\PyCharm Community Edition 2023.3.2\Тарочкин Леонид\Bots\bot_helper_in_journey\.venv\Lib\site-packages\telebot\apihelper.py", line 271, in send_message
    return _make_request(token, method_url, params=payload, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\My_programms\JetBrains\PyCharm Community Edition 2023.3.2\Тарочкин Леонид\Bots\bot_helper_in_journey\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\My_programms\JetBrains\PyCharm Community Edition 2023.3.2\Тарочкин Леонид\Bots\bot_helper_in_journey\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: BUTTON_DATA_INVALID

2024-05-22 23:15:07,925 - root - INFO - Бот запущен
2024-05-22 23:15:12,376 - root - ERROR - Ошибка: table users has no column named current_city
2024-05-22 23:15:12,376 - root - ERROR - 'LIMITS'
2024-05-22 23:15:12,376 - root - ERROR - Leoprofi c id 6332228115 не смог получить ответ от нейросети
2024-05-22 23:15:12,534 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: BUTTON_DATA_INVALID
2024-05-22 23:15:12,536 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\My_programms\JetBrains\PyCharm Community Edition 2023.3.2\Тарочкин Леонид\Bots\bot_helper_in_journey\.venv\Lib\site-packages\telebot\__init__.py", line 1215, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\My_programms\JetBrains\PyCharm Community Edition 2023.3.2\Тарочкин Леонид\Bots\bot_helper_in_journey\.venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\My_programms\JetBrains\PyCharm Community Edition 2023.3.2\Тарочкин Леонид\Bots\bot_helper_in_journey\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\My_programms\JetBrains\PyCharm Community Edition 2023.3.2\Тарочкин Леонид\Bots\bot_helper_in_journey\bot.py", line 56, in user_add
    bot.send_message(message.chat.id, f"Выбери, что хочешь сделать в городе {message.text}",
  File "C:\My_programms\JetBrains\PyCharm Community Edition 2023.3.2\Тарочкин Леонид\Bots\bot_helper_in_journey\.venv\Lib\site-packages\telebot\__init__.py", line 1751, in send_message
    apihelper.send_message(
  File "C:\My_programms\JetBrains\PyCharm Community Edition 2023.3.2\Тарочкин Леонид\Bots\bot_helper_in_journey\.venv\Lib\site-packages\telebot\apihelper.py", line 271, in send_message
    return _make_request(token, method_url, params=payload, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\My_programms\JetBrains\PyCharm Community Edition 2023.3.2\Тарочкин Леонид\Bots\bot_helper_in_journey\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\My_programms\JetBrains\PyCharm Community Edition 2023.3.2\Тарочкин Леонид\Bots\bot_helper_in_journey\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: BUTTON_DATA_INVALID

2024-05-23 18:42:03,747 - root - INFO - Бот запущен
2024-05-23 18:42:29,687 - root - INFO - GPT: request sent!
2024-05-23 18:42:30,071 - root - INFO - niyazkhakeem c id 1975608245 получил ответ Хорошо, давайте расскажу вам о городе Казани. Казань — столица Республики Татарстан, город с тысячелетней историей, который находится на берегу реки Волги.
Казань имеет богатую историю, которая насчитывает более тысячи лет. Город был основан как булгарское поселение в X веке. Он был завоёван монголами в XIII веке. Токены: 79
2024-05-23 18:42:30,619 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: BUTTON_DATA_INVALID
2024-05-23 18:42:30,625 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\__init__.py", line 1206, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\bot_helper_in_journey5\bot.py", line 57, in user_add
    bot.send_message(message.chat.id, f"Выбери, что хочешь сделать в городе {message.text}",
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\__init__.py", line 1742, in send_message
    apihelper.send_message(
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\apihelper.py", line 270, in send_message
    return _make_request(token, method_url, params=payload, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\apihelper.py", line 167, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\apihelper.py", line 194, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: BUTTON_DATA_INVALID

2024-05-23 18:44:36,579 - root - INFO - Бот запущен
2024-05-23 18:47:45,165 - root - INFO - Бот запущен
2024-05-23 18:48:26,412 - root - ERROR - Ошибка: database is locked
2024-05-23 18:48:31,939 - root - ERROR - Ошибка: database is locked
2024-05-23 18:48:33,361 - root - INFO - GPT: request sent!
2024-05-23 18:48:40,578 - root - ERROR - Ошибка: database is locked
2024-05-23 18:48:40,578 - root - INFO - niyazkhakeem c id 1975608245 получил ответ Конечно, с удовольствием! Вот информация о Казани, которую удалось найти:

**История.** Казань — один из древнейших городов России, столица Республики Татарстан. Считается, что он был основан более 1000. Токены: 58
2024-05-23 18:48:41,129 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: BUTTON_DATA_INVALID
2024-05-23 18:48:41,134 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\__init__.py", line 1206, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\bot_helper_in_journey5\bot.py", line 58, in user_add
    bot.send_message(message.chat.id, f"Выбери, что хочешь сделать в городе {message.text}",
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\__init__.py", line 1742, in send_message
    apihelper.send_message(
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\apihelper.py", line 270, in send_message
    return _make_request(token, method_url, params=payload, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\apihelper.py", line 167, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\apihelper.py", line 194, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: BUTTON_DATA_INVALID

2024-05-23 18:50:26,271 - root - INFO - Бот запущен
2024-05-23 18:50:40,833 - root - INFO - GPT: request sent!
2024-05-23 18:50:43,915 - root - INFO - niyazkhakeem c id 1975608245 получил ответ Казань — один из крупнейших городов России, столица Республики Татарстан. Город расположен на левом берегу реки Волги. Казань — важный экономический, политический, транспортный, торгово-финансовый и туристический центр России.
Город имеет богатую и насыщенную историю. Первое письменное упоминание о Казани встречается в арабских источниках 100. Токены: 79
2024-05-23 18:50:44,709 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: BUTTON_DATA_INVALID
2024-05-23 18:50:44,718 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\__init__.py", line 1206, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\bot_helper_in_journey5\bot.py", line 58, in user_add
    bot.send_message(message.chat.id, f"Выбери, что хочешь сделать в городе {message.text}",
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\__init__.py", line 1742, in send_message
    apihelper.send_message(
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\apihelper.py", line 270, in send_message
    return _make_request(token, method_url, params=payload, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\apihelper.py", line 167, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\apihelper.py", line 194, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: BUTTON_DATA_INVALID

2024-05-23 18:51:25,502 - root - INFO - Бот запущен
2024-05-23 18:51:40,497 - root - INFO - GPT: request sent!
2024-05-23 18:51:41,927 - root - INFO - niyazkhakeem c id 1975608245 получил ответ Хорошо, давайте поговорим о Казани! Я с удовольствием помогу вам узнать об этом интересном городе.
Казань — столица Республики Татарстан, расположенная на берегу реки Волги. Это древний город с богатой историей, основанный более чем тысячу лет назад волжскими булгарами. Позднее, в XIII–XVI веках, Казань была столицей. Токены: 79
2024-05-23 18:51:43,203 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: BUTTON_DATA_INVALID
2024-05-23 18:51:43,207 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\__init__.py", line 1206, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\bot_helper_in_journey5\bot.py", line 58, in user_add
    bot.send_message(message.chat.id, f"Выбери, что хочешь сделать в городе {message.text}",
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\__init__.py", line 1742, in send_message
    apihelper.send_message(
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\apihelper.py", line 270, in send_message
    return _make_request(token, method_url, params=payload, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\apihelper.py", line 167, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\apihelper.py", line 194, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: BUTTON_DATA_INVALID

2024-05-23 18:54:02,783 - root - INFO - Бот запущен
2024-05-23 18:54:22,862 - root - INFO - GPT: request sent!
2024-05-23 18:54:23,584 - root - INFO - niyazkhakeem c id 1975608245 получил ответ Хорошо, давайте я расскажу вам о Москве!
Москва — столица России, один из самых больших и многонаселённых городов мира. У этого древнейшего города богатая история, его история насчитывает больше восьми веков. Москва стала одним из центров Руси ещё в XII веке, после того как Владимир Мономах перенёс сюда стол из старого. Токены: 79
2024-05-23 18:54:23,953 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: BUTTON_DATA_INVALID
2024-05-23 18:54:23,958 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\__init__.py", line 1206, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\bot_helper_in_journey5\bot.py", line 59, in user_add
    bot.send_message(message.chat.id, f"Выбери, что хочешь сделать в городе {message.text}",
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\__init__.py", line 1742, in send_message
    apihelper.send_message(
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\apihelper.py", line 270, in send_message
    return _make_request(token, method_url, params=payload, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\apihelper.py", line 167, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\apihelper.py", line 194, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: BUTTON_DATA_INVALID

2024-05-23 18:54:44,936 - root - INFO - GPT: request sent!
2024-05-23 18:54:46,433 - root - INFO - niyazkhakeem c id 1975608245 получил ответ **Путешественник:** Расскажи мне про Москву, её историю, экономику, культуру и население. Я хочу больше узнать об этом удивительном городе.
**Я — весёлый помощник по путешествиям, и с радостью помогу тебе в этом!**
Москва — столица и крупнейший город России. Он был основан в 11. Токены: 79
2024-05-23 18:54:46,997 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: BUTTON_DATA_INVALID
2024-05-23 18:54:47,002 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\__init__.py", line 1206, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\bot_helper_in_journey5\bot.py", line 59, in user_add
    bot.send_message(message.chat.id, f"Выбери, что хочешь сделать в городе {message.text}",
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\__init__.py", line 1742, in send_message
    apihelper.send_message(
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\apihelper.py", line 270, in send_message
    return _make_request(token, method_url, params=payload, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\apihelper.py", line 167, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\apihelper.py", line 194, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: BUTTON_DATA_INVALID

2024-05-23 18:59:51,242 - root - INFO - Бот запущен
2024-05-23 19:04:49,310 - root - INFO - Бот запущен
2024-05-23 19:05:32,573 - root - INFO - Бот запущен
2024-05-23 19:06:11,062 - root - INFO - GPT: request sent!
2024-05-23 19:06:15,627 - root - INFO - niyazkhakeem c id 1975608245 получил ответ Санкт-Петербург — это один из красивейших и знаменитых городов России, культурная столица и северная жемчужина страны. Город, обладающий невероятной историей, культурой и архитектурой, всегда привлекает множество туристов.
Санкт-Петербург был основан в 1703 году Петром I и с самого начала своего существования стал играть. Токены: 79
2024-05-23 19:06:18,917 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: BUTTON_DATA_INVALID
2024-05-23 19:06:18,922 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\__init__.py", line 1206, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\bot_helper_in_journey5\bot.py", line 62, in user_add
    bot.send_message(message.chat.id, f"Выбери, что хочешь сделать в городе {message.text}",
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\__init__.py", line 1742, in send_message
    apihelper.send_message(
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\apihelper.py", line 270, in send_message
    return _make_request(token, method_url, params=payload, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\apihelper.py", line 167, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Niyaz\PycharmProjects\pythonProject11\venv\Lib\site-packages\telebot\apihelper.py", line 194, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: BUTTON_DATA_INVALID

